-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID,
    B.AUTHOR_NAME,
    A.CATEGORY,
    SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A
INNER JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES C
ON A.BOOK_ID = C.BOOK_ID
AND YEAR(C.SALES_DATE) = 2022
AND MONTH(C.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID, A.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC