-- 코드를 입력하세요
SELECT
    B.FOOD_TYPE,
    B.REST_ID,
    B.REST_NAME,
    B.FAVORITES
FROM REST_INFO B
WHERE B.FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO A
    WHERE A.FOOD_TYPE = B.FOOD_TYPE
)
ORDER BY B.FOOD_TYPE DESC