-- 코드를 작성해주세요
SELECT 
        ROUTE,	
        CONCAT(ROUND(SUM(COALESCE(D_BETWEEN_DIST, 0)), 1),'km') AS TOTAL_DISTANCE, -- 총누계거리
        CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE -- 평균 역 사이 거리
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(COALESCE(D_BETWEEN_DIST, 0)), 1) DESC;