-- 가상 테이블(0부터 23까지 hour)
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME
    WHERE HOUR < 23
)

SELECT 
    T.HOUR AS HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME T
LEFT JOIN ANIMAL_OUTS A 
ON T.HOUR = HOUR(A.DATETIME)
AND HOUR(A.DATETIME) BETWEEN 0 AND 23
GROUP BY HOUR
ORDER BY HOUR
