-- 코드를 입력하세요
SELECT A.WRITER_ID USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B
ON B.USER_ID = A.WRITER_ID
AND A.STATUS = 'DONE'
WHERE 1=1
GROUP BY A.WRITER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY SUM(A.PRICE)


