
SELECT 
    MONTH(B.START_DATE) AS MONTH,
    B.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE B.CAR_ID IN (
    SELECT  -- 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차 ID 조회
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE 1=1
        AND START_DATE <= '2022-10-31'
        AND START_DATE >= '2022-08-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
AND B.START_DATE <= '2022-10-31'
AND B.START_DATE >= '2022-08-01'
GROUP BY MONTH(B.START_DATE), B.CAR_ID
ORDER BY MONTH ASC, B.CAR_ID DESC;