-- 코드를 작성해주세요
SELECT A.SCORE,
    A.EMP_NO,
    B.EMP_NAME,
    B.POSITION,
    B.EMAIL
FROM (
    SELECT
        EMP_NO,
        SUM(SCORE) AS SCORE,
        YEAR
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO, YEAR
) A
JOIN HR_EMPLOYEES B 
ON A.EMP_NO = B.EMP_NO
ORDER BY A.SCORE DESC
LIMIT 1;
