-- 코드를 입력하세요
/*
SELECT 
    CATEGORY, 
    AS TOTAL_SALES
FROM BOOK A
ORDER BY CATEGORY ASC
;*/

SELECT 
    B.CATEGORY, 
    SUM(A.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT 
        SUM(SALES) AS SALES, 
        BOOK_ID
    FROM BOOK_SALES
    WHERE 1=1 
    AND YEAR(SALES_DATE) = '2022'
    AND MONTH(SALES_DATE) = '1'
    GROUP BY BOOK_ID
) A 
ON B.BOOK_ID = A.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
