-- 코드를 입력하세요
SELECT
    F.CATEGORY,
    A.MAX_PRICE,
    F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT 
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) A ON
F.PRICE = A.MAX_PRICE
AND F.CATEGORY = A.CATEGORY
ORDER BY A.MAX_PRICE DESC
